[build]
  command = "gatsby build"
  publish = "public"

[dev]
  command = "gatsby develop"

[functions]
  node_bundler = "esbuild"


[build.environment]
  NODE_OPTIONS = "--openssl-legacy-provider"
  NODE_VERSION = "16"

