[build]
  command = "gatsby build"
  publish = "public"

[build.environment]
  NODE_OPTIONS = "--openssl-legacy-provider"


[dev]
  command = "gatsby develop"

[functions]
  node_bundler = "esbuild"



